name: autobench
on: push
jobs:
  bench:
    name: Benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: antongolub/action-setup-bun@v1
      - run: bun install

      - uses: actions/setup-go@v3.5.0
      - run: go install github.com/codesenberg/bombardier@latest
      - run: export GOPATH=$HOME/go && export PATH=$PATH:$GOROOT/bin:$GOPATH/bin

      - run: bun bench